---
title: "Visualizations"
author: "Brett Graham"
date: "3/23/2018"
output: html_document
--- 
### Matt's Chunks for visualization
```{r}
# Relationship between clicks and applies per state
ggplot(indeedState, aes(x= stateClicks, y=stateApplies, label=State)) + geom_point() + geom_text(aes(label=State), hjust= 0, vjust = 0, alpha=0.5)
```
Linear relationship between clicks and stateApplies, more clicks more applies. Applies per click is standard across states.


Populaton concentration impacts need for indeed?
```{r}
# Visualization of clicks per unemployed people in state
ggplot(indeedState, aes(x= State, y = clicksPerUnemployed)) + geom_col()
```


```{r}
# Visualization of clicks per unemployed people in state
ggplot(indeedState, aes(x= jobPostings, y = stateClicks)) + 
  geom_point() 
```


Map of U.S. with residual based on model (details filled in by brett) glyphs sized for city population placed in city location
```{r}
# Filtering for visualization (NEED TO RUN RESIDUAL IN MODELING.RMD)
filtIndeedCity <- indeedCityModel %>%
  filter(Residual > 17000 | Residual < -17000)
```

```{r}
lon <- c(-130, -60)
lat <- c(20, 55)

myLocation <- c(lon = mean(lon), lat = mean(lat))
map<-get_map(location=myLocation, zoom = 3, maptype = "terrain",
             source='google', color = 'color')

meanRes <- mean(indeedCityModel$Residual)

map <- ggmap(data = filtIndeedCity, map) + 
  geom_point(data = filtIndeedCity, 
             aes(x = long,
                 y = lat, 
                 size =  log(abs(Residual)), 
                 colour = Residual))  +
  scale_size(range = c(0.5, 7)) + 
  scale_colour_gradient2(midpoint = meanRes, 
                         low = '#DC1437', 
                         mid = 'white', 
                         high = '#000080') + 
  scale_size(range = c(0, 15)) + 
  scale_x_continuous(limits = lon, expand = c(0,0)) + 
  scale_y_continuous(limits = lat, expand = c(0,0)) 
  

```

